### ISSUE TITLE
Error when writing text with special character

### ISSUE THREAD

**Issue by OlivierJourdan** [JamesMc86/G-CLI#132]
G-CLI version [3.0.0 beta1](https://github.com/JamesMc86/G-CLI/releases/tag/v3.0.0-beta1)

-------

I have the following error when writing a text with a special character with the `Write String` function:

`Comms Error: Message contents cannot be read as UTF8`

It would be nice to find a fix when the string you want to write is not a constant (file path, for example).

NOTE: I already implemented a quick and dirty workaround—no emergency to implement a fix for me.

For the record, here is my fix
<img width="336" alt="image" src="https://user-images.githubusercontent.com/58081359/212061260-918892a9-5bd9-4ac9-9164-d6ba7c0279a8.png">

**Comment by JamesMc86** [comment]
Thanks Olivier - one of those simple things that are so complicated!

I'll take a look at what I can do to support the extended ASCII tables.

**Comment by OlivierJourdan** [comment]
I didn't dive into the code to see where the issue was. So, I haven't ideas how to fix it properly.
From a user standpoint, I'm fine if extended characters are not displayed. I'm sure your time could be more valuable on other issues.
IMO, the important thing is not to be stopped by an extended character.

**Comment by JamesMc86** [comment]
Ah no worries, wasn't sure if it is something you might have come across elsewhere. Turns out extended ASCII like LabVIEW is a minefield for compatibility

We can definitely make it robust to this as you say. There are 3 options to consider:

1. Simplest is to do a lossy conversion to UTF8 in Rust.
2. We can convert to UTF8 in LabVIEW. There appears to be a function for this in described at https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z00000159jOSAQ&l=en-GB
3. We can convert from ExtendedASCII to UTF8 in rust. There is an encoding library but we would have to determine the current code page from the Windows API - and consider cross platform concerns

I'm inclined towards 2 although sounds like the tools provided just wrap the Windows API so perhaps should be 3 and we can use them to ensure we are calling the correct methods.

**Comment by OlivierJourdan** [comment]
I'm not sure 2 will work. If I remember, that was the first thing I tried, and it was unsuccessful.

**Comment by JamesMc86** [comment]
I'll have a play - I've just looked in the NI Unicode tools and there is a wrapper for a private primitive which is text to UTF-8 and appears to be cross-platform.

Sounds like what we would need but perhaps there are limitations?

Alternatively I can copy their method for ASCII to UTF-16 using Windows calls at least - I can see the correct options now and wrap then on the Rust side where there are easier conversions from UTF-16 to UTF-8 (the internal representation required)

**Comment by OlivierJourdan** [comment]
Nice. If you want me to test something, just let me know.

**Comment by JamesMc86** [comment]
The next release should fix these issues. Hopefully, it will appear on Github today!

**Comment by OlivierJourdan** [comment]
Excellent! Thanks for this @JamesMc86 👏
